<?php

return [
    'name' => '커뮤니티',
    'version' => '2026.05.008',
    'type' => 'module',
    'description' => '게시판형 커뮤니티 모듈입니다.',
    'admin' => [
        'category' => 'community',
        'category_label' => '커뮤니티',
        'category_order' => 35,
        'menu_order' => 10,
        'icon' => ['type' => 'symbol', 'name' => 'message-circle'],
        'stylesheets' => ['assets/community-admin.css'],
    ],
    'saanraan' => [
        'min_version' => '0.2.0',
        'tested_with' => ['0.2.0'],
        'module_contract' => '2.0',
    ],
    'requires' => [
        'modules' => ['member', 'admin'],
    ],
    'contracts' => [
        'provides' => [
            'paths.php',
            'admin-menu.php',
            'menu-links.php',
            'extension-points.php',
            'privacy-export.php',
            'sitemap.php',
            'member-group-rules.php',
            'dashboard.php',
        ],
    ],
    'service_domain' => [
        'main_page' => [
            'label' => '커뮤니티 홈',
            'path' => '/community',
        ],
    ],
    'settings' => [
        'posts_per_page' => 20,
        'comments_per_page' => 50,
        'post_create_window_seconds' => 300,
        'post_create_limit' => 10,
        'comment_create_window_seconds' => 300,
        'comment_create_limit' => 30,
        'report_create_window_seconds' => 300,
        'report_create_limit' => 20,
        'message_create_window_seconds' => 300,
        'message_create_limit' => 20,
        'attachment_max_bytes' => 2097152,
        'image_uploads_enabled' => true,
        'file_uploads_enabled' => false,
        'file_attachment_max_bytes' => 5242880,
        'file_attachment_max_count' => 3,
        'file_allowed_extensions' => ['pdf', 'txt', 'csv', 'zip', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'hwp'],
        'level_enabled' => false,
        'level_auto_recalculate' => false,
        'level_post_score' => 10,
        'level_comment_score' => 2,
        'access_condition_priority' => 'both_required',
        'message_write_policy' => 'member',
        'message_write_group_keys' => [],
        'message_write_min_level' => 0,
        'theme_key' => 'basic',
    ],
];
