CREATE TABLE IF NOT EXISTS sr_pages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    slug VARCHAR(120) NOT NULL,
    title VARCHAR(160) NOT NULL,
    summary TEXT NULL,
    body_text MEDIUMTEXT NOT NULL,
    body_format VARCHAR(20) NOT NULL DEFAULT 'plain',
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    asset_access_enabled TINYINT(1) NOT NULL DEFAULT 0,
    asset_module VARCHAR(20) NOT NULL DEFAULT 'point',
    asset_access_amount BIGINT NOT NULL DEFAULT 0,
    asset_charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    asset_action_enabled TINYINT(1) NOT NULL DEFAULT 0,
    asset_action_module VARCHAR(20) NOT NULL DEFAULT 'point',
    asset_action_amount BIGINT NOT NULL DEFAULT 0,
    asset_action_direction VARCHAR(20) NOT NULL DEFAULT 'grant',
    asset_action_label VARCHAR(80) NOT NULL DEFAULT '완료',
    banner_before_content_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    banner_after_content_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    popup_layer_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    seo_title VARCHAR(160) NOT NULL DEFAULT '',
    seo_description VARCHAR(255) NOT NULL DEFAULT '',
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_pages_slug (slug),
    KEY idx_sr_pages_status_slug (status, slug),
    KEY idx_sr_pages_status_updated (status, updated_at),
    KEY idx_sr_pages_asset_access (asset_access_enabled, asset_module),
    KEY idx_sr_pages_asset_action (asset_action_enabled, asset_action_module),
    KEY idx_sr_pages_created_by (created_by, id),
    KEY idx_sr_pages_updated_by (updated_by, id)
);

CREATE TABLE IF NOT EXISTS sr_page_revisions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    page_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(160) NOT NULL,
    summary TEXT NULL,
    body_text MEDIUMTEXT NOT NULL,
    body_format VARCHAR(20) NOT NULL DEFAULT 'plain',
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    asset_access_enabled TINYINT(1) NOT NULL DEFAULT 0,
    asset_module VARCHAR(20) NOT NULL DEFAULT 'point',
    asset_access_amount BIGINT NOT NULL DEFAULT 0,
    asset_charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    asset_action_enabled TINYINT(1) NOT NULL DEFAULT 0,
    asset_action_module VARCHAR(20) NOT NULL DEFAULT 'point',
    asset_action_amount BIGINT NOT NULL DEFAULT 0,
    asset_action_direction VARCHAR(20) NOT NULL DEFAULT 'grant',
    asset_action_label VARCHAR(80) NOT NULL DEFAULT '완료',
    banner_before_content_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    banner_after_content_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    popup_layer_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_page_revisions_page_id (page_id, id),
    KEY idx_sr_page_revisions_created_by (created_by, id)
);

CREATE TABLE IF NOT EXISTS sr_page_asset_access_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    page_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    asset_module VARCHAR(20) NOT NULL,
    transaction_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reference_type VARCHAR(60) NOT NULL,
    reference_id VARCHAR(120) NOT NULL,
    access_kind VARCHAR(40) NOT NULL DEFAULT 'view',
    charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    amount BIGINT NOT NULL,
    dedupe_key VARCHAR(160) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_page_asset_access_dedupe (dedupe_key),
    KEY idx_sr_page_asset_access_account (account_id, created_at),
    KEY idx_sr_page_asset_access_page (page_id, account_id),
    KEY idx_sr_page_asset_access_transaction (asset_module, transaction_id)
);

CREATE TABLE IF NOT EXISTS sr_page_files (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    page_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(160) NOT NULL,
    original_name VARCHAR(120) NOT NULL,
    stored_name VARCHAR(120) NOT NULL,
    storage_path VARCHAR(255) NOT NULL,
    storage_driver VARCHAR(20) NOT NULL DEFAULT 'local',
    storage_key VARCHAR(255) NOT NULL DEFAULT '',
    mime_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    checksum_sha256 CHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    asset_download_enabled TINYINT(1) NOT NULL DEFAULT 0,
    asset_module VARCHAR(20) NOT NULL DEFAULT 'point',
    asset_download_amount BIGINT NOT NULL DEFAULT 0,
    asset_charge_policy VARCHAR(20) NOT NULL DEFAULT 'once',
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sr_page_files_page_status (page_id, status, id),
    KEY idx_sr_page_files_asset_download (asset_download_enabled, asset_module),
    KEY idx_sr_page_files_storage (storage_driver, storage_key),
    KEY idx_sr_page_files_checksum (checksum_sha256)
);

CREATE TABLE IF NOT EXISTS sr_page_asset_action_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    page_id BIGINT UNSIGNED NOT NULL,
    account_id BIGINT UNSIGNED NOT NULL,
    asset_module VARCHAR(20) NOT NULL,
    transaction_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reference_type VARCHAR(60) NOT NULL,
    reference_id VARCHAR(120) NOT NULL,
    action_key VARCHAR(40) NOT NULL DEFAULT 'complete',
    direction VARCHAR(20) NOT NULL,
    amount BIGINT NOT NULL,
    dedupe_key VARCHAR(160) NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sr_page_asset_action_dedupe (dedupe_key),
    KEY idx_sr_page_asset_action_account (account_id, created_at),
    KEY idx_sr_page_asset_action_page (page_id, account_id),
    KEY idx_sr_page_asset_action_transaction (asset_module, transaction_id)
);
